// @ts-nocheck
export const mockTokens = [
  {
    ca: "8SYciweZS...MTZGNS",
    name: "Solana",
    icon: "https://cryptologos.cc/logos/solana-sol-logo.png",
    description: "Fast blockchain for DeFi and NFTs",
    volumeUsd: 1250000,
    marketCapUsd: 45000000000,
    priceUsd: 145.23,
    percent: 65,
    holders: 1200000,
    holdersPercent: 12,
    buys: 320,
    sells: 210,
    time: "2025-09-24 14:20",
    x: "https://x.com/solana",
    website: "https://solana.com",
    creator: "So11111111111111111111111111111111111111112",
  },
  {
    ca: "B4BU8JBW81...nwmA",
    name: "MyToken",
    icon: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
    description: "Experimental ERC-20 token",
    volumeUsd: 245000,
    marketCapUsd: 7200000,
    priceUsd: 0.0023,
    percent: 33,
    holders: 5342,
    holdersPercent: 3,
    buys: 50,
    sells: 80,
    time: "2025-09-24 12:00",
    x: "",
    website: "",
    creator: "0x1234567890abcdef",
  },
];

// @ts-nocheck
export const mockRewards = [
  {
    id: 1,
    title: "Welcome Bonus",
    description: "Reward for joining the platform",
    points: 100,
    date: "2025-09-01",
    status: "Completed",
    icon: "🎁",
  },
  {
    id: 2,
    title: "First Trade",
    description: "Bonus for completing your first token trade",
    points: 250,
    date: "2025-09-10",
    status: "Completed",
    icon: "💸",
  },
  {
    id: 3,
    title: "Portfolio Holder",
    description: "Reward for holding 3+ tokens in your portfolio",
    points: 500,
    date: "2025-09-20",
    status: "In Progress",
    icon: "📊",
  },
  {
    id: 4,
    title: "Referral",
    description: "Invite a friend and earn bonus points",
    points: 300,
    date: "2025-09-22",
    status: "Completed",
    icon: "🤝",
  },
  {
    id: 5,
    title: "Top Trader",
    description: "Be in the top 10 traders this week",
    points: 1000,
    date: "2025-09-28",
    status: "Locked",
    icon: "🏆",
  },
];

// src/mockTokens.ts
// Моки портфеля для таблицы/дашборда

export type Token = {
  id: string;
  symbol: string;
  name: string;
  icon?: string; // эмодзи или буква/иконка
  logoUrl?: string; // если захочешь показывать картинку
  balance: number; // количество токена
  price: number; // текущая цена в $
  change24h: number; // % за 24ч
  change7d: number; // % за 7д
  costBasis: number; // средняя цена покупки
  category: string; // тег/категория (для Allocation)
};

// Набор «от души»: немного L1, DEX, стейблов и мемов
export const mockTokensPortfolio: Token[] = [
  {
    id: "sol",
    symbol: "SOL",
    name: "Solana",
    icon: "🟣",
    balance: 12.34,
    price: 156.21,
    change24h: 4.2,
    change7d: 12.7,
    costBasis: 120.0,
    category: "Layer1",
  },
  {
    id: "usdc",
    symbol: "USDC",
    name: "USD Coin",
    icon: "🔵",
    balance: 2500,
    price: 1,
    change24h: 0.0,
    change7d: 0.0,
    costBasis: 1.0,
    category: "Stablecoin",
  },
  {
    id: "bonk",
    symbol: "BONK",
    name: "Bonk",
    icon: "🐶",
    balance: 1_250_000,
    price: 0.000031,
    change24h: -3.9,
    change7d: 8.3,
    costBasis: 0.000028,
    category: "Meme",
  },
  {
    id: "jup",
    symbol: "JUP",
    name: "Jupiter",
    icon: "🟩",
    balance: 420.69,
    price: 1.42,
    change24h: 1.1,
    change7d: 5.6,
    costBasis: 1.28,
    category: "DEX",
  },
  {
    id: "eth",
    symbol: "ETH",
    name: "Ethereum",
    icon: "🟠",
    balance: 0.85,
    price: 3321.4,
    change24h: 2.3,
    change7d: 6.1,
    costBasis: 2800,
    category: "Layer1",
  },
  {
    id: "wif",
    symbol: "WIF",
    name: "dogwifhat",
    icon: "🎩",
    balance: 980,
    price: 2.31,
    change24h: -1.8,
    change7d: 9.2,
    costBasis: 1.95,
    category: "Meme",
  },
  {
    id: "pyth",
    symbol: "PYTH",
    name: "Pyth Network",
    icon: "🟨",
    balance: 1350,
    price: 0.43,
    change24h: 0.7,
    change7d: 4.9,
    costBasis: 0.39,
    category: "Oracle",
  },
  {
    id: "jito",
    symbol: "JTO",
    name: "Jito",
    icon: "⚡",
    balance: 520,
    price: 2.68,
    change24h: 3.5,
    change7d: 11.3,
    costBasis: 2.15,
    category: "Liquid Staking",
  },
  {
    id: "ray",
    symbol: "RAY",
    name: "Raydium",
    icon: "💧",
    balance: 800,
    price: 1.12,
    change24h: 1.9,
    change7d: 7.6,
    costBasis: 0.95,
    category: "DEX",
  },
  {
    id: "tia",
    symbol: "TIA",
    name: "Celestia",
    icon: "🟪",
    balance: 75.5,
    price: 7.34,
    change24h: -0.9,
    change7d: 3.1,
    costBasis: 6.6,
    category: "Data Availability",
  },
  {
    id: "arb",
    symbol: "ARB",
    name: "Arbitrum",
    icon: "🧊",
    balance: 620,
    price: 0.98,
    change24h: 2.1,
    change7d: 4.2,
    costBasis: 0.85,
    category: "L2",
  },
  {
    id: "hnt",
    symbol: "HNT",
    name: "Helium",
    icon: "📡",
    balance: 190,
    price: 6.42,
    change24h: 4.8,
    change7d: 10.2,
    costBasis: 5.1,
    category: "DePIN",
  },
  {
    id: "rndr",
    symbol: "RNDR",
    name: "Render",
    icon: "🖥️",
    balance: 75,
    price: 6.95,
    change24h: -2.1,
    change7d: 1.8,
    costBasis: 6.2,
    category: "AI",
  },
  {
    id: "swrd",
    symbol: "SWRD",
    name: "Sword Finance",
    icon: "🗡️",
    balance: 5000,
    price: 0.041,
    change24h: 6.4,
    change7d: 21.3,
    costBasis: 0.033,
    category: "Perps",
  },
  {
    id: "usdt",
    symbol: "USDT",
    name: "Tether",
    icon: "🟢",
    balance: 1200,
    price: 1,
    change24h: 0.0,
    change7d: 0.0,
    costBasis: 1.0,
    category: "Stablecoin",
  },
];
