export const tokens = [
  {
    icon: "/icons/mask.png",
    name: "$MaskCoin / MetaMask Coin",
    description: "MetaMask USD ($mUSD) is now live. The best way in and out...",
    ca: "7n6Q...rKPj",
    volume: "$44K",
    buys: 1,
    sells: 0,
    marketCap: "$228.9M",
    price: "$0.2180",
    percent: 25,
    holders: 120,
    holdersPercent: 12,
    time: "1s ago",
    author: "5teC...RY2D",
  },
  {
    icon: "/icons/metamask.png",
    name: "MetaMask / MetaMask Coin",
    description: "Unofficial Official Metamask Token. Seeing as Dan doesn’t...",
    ca: "9hSD...SLuF",
    volume: "$68K",
    buys: 168,
    sells: 122,
    marketCap: "$2.0B",
    price: "$1.87",
    percent: 60,
    holders: 450,
    holdersPercent: 35,
    time: "49s ago",
    author: "gCFC...mu0M",
  },
  {
    icon: "/icons/deepseek.png",
    name: "DeepSeekAI",
    description: "AI-driven research assistant.",
    ca: "5Ykg...LpAM",
    volume: "$0",
    buys: 0,
    sells: 0,
    marketCap: "$0.0",
    price: "$0.0000",
    percent: 85,
    holders: 320,
    holdersPercent: 28,
    time: "3m ago",
    author: "4iaT...cTbJ",
  },
  {
    icon: "/icons/tux.png",
    name: "TUX / TUX The Penguin",
    description: "The long awaited financial freedom which you ever wished...",
    ca: "FzU7...daos",
    volume: "$15K",
    buys: 1,
    sells: 0,
    marketCap: "$19.1M",
    price: "$0.01818",
    percent: 40,
    holders: 210,
    holdersPercent: 18,
    time: "4m ago",
    author: "AY3z...9Qay",
  },
];
